interface Configuration {
    languages: Array<Description>;
    game: Array<Description>;
    cluster: Array<Cluster>;
    mixing: Array<Description>;
    traits: Array<Description>;
    geyser: Array<Description>;
}

const configuration: Configuration = {
    languages: [
        { type: 0, key: "en", name: "English" },
        { type: 1, key: "zh-CN", name: "简体中文" },
    ],
    game: [
        { type: 0, key: "", name: "Base Game" },
        { type: 1, key: "", name: "Classic" },
        { type: 2, key: "", name: "Spaced Out!" },
    ],
    // prettier-ignore
    cluster: [
        { type: 0, max: 0, prefix: "SNDST-A",   name:"Terra",                               traits: "" },
        { type: 0, max: 4, prefix: "OCAN-A",    name:"Oceania",                             traits: "Z9ABCDEFGHIJKLMNOPQ" },
        { type: 0, max: 4, prefix: "S-FRZ",     name:"Rime",                                traits: "Z9ABCDEFGHIJKLMNOPQ" },
        { type: 0, max: 4, prefix: "LUSH-A",    name:"Verdante",                            traits: "Z9ABCDEFGHIJKLMNOPQ" },
        { type: 0, max: 4, prefix: "FRST-A",    name:"Arboria",                             traits: "Z9ABCDEFGHIJKLMNOPQ" },
        { type: 0, max: 4, prefix: "VOLCA",     name:"Volcanea",                            traits: "Z9ABCDEFGHIJKLMNOPQ" },
        { type: 0, max: 4, prefix: "BAD-A",     name:"The Badlands",                        traits: "Z9ABCDEFGHIJKLMNOPQ" },
        { type: 0, max: 4, prefix: "HTFST-A",   name:"Aridio",                              traits: "Z9ABCDEFGHIJKLMNOPQ" },
        { type: 0, max: 4, prefix: "OASIS-A",   name:"Oasisse",                             traits: "Z9ABCDEFGHIJKLMNOPQ" },
        { type: 0, max: 4, prefix: "CER-A",     name:"Ceres",                               traits: "Z9ABCEFGHILMNOQ" },
        { type: 0, max: 4, prefix: "CERS-A",    name:"Blasted Ceres",                       traits: "Z9ABCFGHILMOQ" },
        { type: 0, max: 4, prefix: "PRE-A",     name:"Relica",                              traits: "Z9ABCEFGHIKLMOQ" },
        { type: 0, max: 2, prefix: "PRES-A",    name:"RelicAAAAGH",                         traits: "Z9ABCEGIKLMO" },
        { type: 0, max: 4, prefix: "AQU-A",     name:"Marinea",                             traits: "Z9ABCEFGHIKLMOQ" },
        { type: 1, max: 0, prefix: "V-SNDST-C", name:"Terra Cluster",                       traits: "" },
        { type: 1, max: 4, prefix: "V-OCAN-C",  name:"Oceania Cluster",                     traits: "Z9ABCDEFGHIKLMNO1358" },
        { type: 1, max: 4, prefix: "V-SWMP-C",  name:"Squelchy Cluster",                    traits: "Z9ABCDEFGHIKLMNO1358" },
        { type: 1, max: 4, prefix: "V-SFRZ-C",  name:"Rime Cluster",                        traits: "Z9ABCDEFGHIKLMNO1358" },
        { type: 1, max: 4, prefix: "V-LUSH-C",  name:"Verdante Cluster",                    traits: "Z9ABCDEFGHIKLMNO1358" },
        { type: 1, max: 4, prefix: "V-FRST-C",  name:"Arboria Cluster",                     traits: "Z9ABCDEFGHIKLMNO1358" },
        { type: 1, max: 4, prefix: "V-VOLCA-C", name:"Volcanea Cluster",                    traits: "Z9ABCDEFGHIKLMNO1358" },
        { type: 1, max: 4, prefix: "V-BAD-C",   name:"The Badlands Cluster",                traits: "Z9ABCDEFGHIKLMNO1358" },
        { type: 1, max: 4, prefix: "V-HTFST-C", name:"Aridio Cluster",                      traits: "Z9ABCDEFGHIKLMNO1358" },
        { type: 1, max: 4, prefix: "V-OASIS-C", name:"Oasisse Cluster",                     traits: "Z9ABCDEFGHIKLMNO1358" },
        { type: 1, max: 4, prefix: "V-CER-C",   name:"Ceres Cluster",                       traits: "Z9ABCEFGHILMNO158" },
        { type: 1, max: 4, prefix: "V-CERS-C",  name:"Blasted Ceres Cluster",               traits: "Z9ABCFGHILMO158" },
        { type: 1, max: 4, prefix: "V-PRE-C",   name:"Relica Cluster",                      traits: "Z9ABCEFGHIKLMO58" },
        { type: 1, max: 2, prefix: "V-PRES-C",  name:"RelicAAAAGH Cluster",                 traits: "Z9ABCEGIKLMO5" },
        { type: 1, max: 4, prefix: "V-AQU-C",   name:"Marinea Cluster",                     traits: "Z9ABCEFGHIKLMO158" },
        { type: 2, max: 0, prefix: "SNDST-C",   name:"Terrania Cluster",                    traits: "" },
        { type: 2, max: 4, prefix: "AQU-C",     name:"Marinea Minor Cluster",               traits: "Z9ABCFGILMO15" },
        { type: 2, max: 4, prefix: "PRE-C",     name:"Relica Minor Cluster",                traits: "Z9ABCEFGIKLMO58" },
        { type: 2, max: 4, prefix: "CER-C",     name:"Ceres Minor Cluster",                 traits: "Z9ABCEFGILMNO158" },
        { type: 2, max: 4, prefix: "FRST-C",    name:"Folia Cluster",                       traits: "Z9ABCEFGIKLMNO1578" },
        { type: 2, max: 4, prefix: "SWMP-C",    name:"Quagmiris Cluster",                   traits: "Z9ABCEFGIKLMNO1578" },
        { type: 2, max: 2, prefix: "M-SWMP-C",  name:"Moonlet Cluster - Metallic Swampy",   traits: "ZABCEGKLMNO1245678" },
        { type: 2, max: 2, prefix: "M-BAD-C",   name:"Moonlet Cluster - The Desolands",     traits: "ZABCDEGKLMNO124568" },
        { type: 2, max: 2, prefix: "M-FRZ-C",   name:"Moonlet Cluster - Frozen Forest",     traits: "ZABCEGKLMNO124568" },
        { type: 2, max: 2, prefix: "M-FLIP-C",  name:"Moonlet Cluster - Flipped",           traits: "ZABCGLMO25" },
        { type: 2, max: 2, prefix: "M-RAD-C",   name:"Moonlet Cluster - Radioactive Ocean", traits: "ZABCEGLMO124568" },
        { type: 2, max: 2, prefix: "M-CERS-C",  name:"Moonlet Cluster - Ceres Mantle",      traits: "ZABCEGKLMO1578" },
    ],
    mixing: [
        { type: 16, key: "d2p1", name: "The Frosty Planet Pack" },
        { type: 12, key: "d2f1", name: "Ceres Fragment" },
        { type: 15, key: "d2b1", name: "Ice Cave Biome" },
        { type: 14, key: "d2b2", name: "Cool Pool Biome" },
        { type: 13, key: "d2b3", name: "Nectar Biome" },
        { type: 11, key: "d3p1", name: "The Bionic Booster Pack" },
        { type: 10, key: "d4p1", name: "The Prehistoric Planet Pack" },
        { type: 6, key: "d4f1", name: "Relica Fragment" },
        { type: 9, key: "d4b1", name: "Garden Biome" },
        { type: 8, key: "d4b2", name: "Feather Biome" },
        { type: 7, key: "d4b3", name: "Wetlands Biome" },
        { type: 5, key: "d5p1", name: "The Aquatic Planet Pack" },
        { type: 0, key: "d5f1", name: "Marinea Fragment" },
        { type: 4, key: "d5b1", name: "Beach Biome" },
        { type: 3, key: "d5b2", name: "Reef Biome" },
        { type: 2, key: "d5b3", name: "Kelp Forest Biome" },
        { type: 1, key: "d5b4", name: "Abyss Biome" },
    ],
    geyser: [
        { type: 1, key: "steam", name: "Cool Steam Vent" },
        { type: 0, key: "hot_steam", name: "Steam Vent" },
        { type: 1, key: "hot_water", name: "Water Geyser" },
        { type: 1, key: "slush_water", name: "Cool Slush Geyser" },
        { type: 1, key: "filthy_water", name: "Polluted Water Vent" },
        { type: 1, key: "slush_salt_water", name: "Cool Salt Slush Geyser" },
        { type: 1, key: "salt_water", name: "Salt Water Geyser" },
        { type: 0, key: "small_volcano", name: "Minor Volcano" },
        { type: 0, key: "big_volcano", name: "Volcano" },
        { type: 2, key: "liquid_co2", name: "Carbon Dioxide Geyser" },
        { type: 2, key: "hot_co2", name: "Carbon Dioxide Vent" },
        { type: 2, key: "hot_hydrogen", name: "Hydrogen Vent" },
        { type: 2, key: "hot_po2", name: "Hot Polluted Oxygen Vent" },
        { type: 2, key: "slimy_po2", name: "InFectious Polluted Oxygen Vent" },
        { type: 2, key: "chlorine_gas", name: "Chlorine Gas Vent" },
        { type: 0, key: "methane", name: "Natural Gas Geyser" },
        { type: 0, key: "molten_copper", name: "Copper Volcano" },
        { type: 0, key: "molten_iron", name: "Iron Volcano" },
        { type: 0, key: "molten_gold", name: "Gold Volcano" },
        { type: 0, key: "molten_aluminum", name: "Aluminum Volcano" },
        { type: 0, key: "molten_cobalt", name: "Cobalt Volcano" },
        { type: 0, key: "oil_drip", name: "Leaky Oil Fissure" },
        { type: 0, key: "liquid_sulfur", name: "Liquid Sulfur Geyser" },
        { type: 0, key: "chlorine_gas_cool", name: "Cool Chlorine Gas Vent" },
        { type: 0, key: "molten_tungsten", name: "Tungsten Volcano" },
        { type: 0, key: "molten_niobium", name: "Niobium Volcano" },
        { type: 0, key: "murky_brine", name: "Polluted Brine Vent" },
        { type: 0, key: "oil_reservoir", name: "Oil Reservoir" },
        { type: 0, key: "SmallReefGeyser", name: "Tidal Spring" },
        { type: 0, key: "UnderwaterVent", name: "Thermal Gas Fissure" },
        { type: 0, key: "receiver", name: "Supply Teleporter Output" },
        { type: 0, key: "sender", name: "Supply Teleporter Input" },
        { type: 0, key: "teleporter", name: "Teleporter Transmitter" },
        { type: 0, key: "cryopod", name: "Cryotank 3000" },
        { type: 0, key: "printpod", name: "Printing Pod" },
    ],
    traits: [
        { type: 0, key: "0", name: "No Traits" },
        { type: 0, key: "1", name: "Crashed Satellites" },
        { type: 0, key: "2", name: "Frozen Friend" },
        { type: 0, key: "3", name: "Irregular Oil" },
        { type: 0, key: "4", name: "Lush Core" },
        { type: 0, key: "5", name: "Metallic Caves" },
        { type: 0, key: "6", name: "Radioactive Crust" },
        { type: 0, key: "7", name: "Subsurface Ocean" },
        { type: 0, key: "8", name: "Volcanic Activity" },
        { type: 2, key: "9", name: "Large Boulders" },
        { type: 0, key: "A", name: "Medium Boulders" },
        { type: 2, key: "B", name: "Mixed Boulders" },
        { type: 0, key: "C", name: "Small Boulders" },
        { type: 0, key: "D", name: "Trapped Oil" },
        { type: 0, key: "E", name: "Frozen Core" },
        { type: 1, key: "F", name: "Geoactive" },
        { type: 1, key: "G", name: "Geodes" },
        { type: 2, key: "H", name: "Geodormant" },
        { type: 0, key: "I", name: "Large Claciers" },
        { type: 0, key: "J", name: "Irregular Oil" },
        { type: 0, key: "K", name: "Magma Channels" },
        { type: 2, key: "L", name: "Metal Poor" },
        { type: 1, key: "M", name: "Metal Rich" },
        { type: 0, key: "N", name: "Alternate Pod Location" },
        { type: 0, key: "O", name: "Slime Molds" },
        { type: 0, key: "P", name: "Subsurface Ocean" },
        { type: 0, key: "Q", name: "Volcanic Activity" },
        { type: 0, key: "Z", name: "Any Trait" },
    ],
};

export default configuration;
